### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by earthpwn** [Tospaa/changeListener#1]
Hi Mr Tospaa,

I am really enjoying this sh*t. Needed something like this and recalled that you have already done it.
Trink trink, it works like charm. Thanks abe!
And I knew I could find it here because you are a very helpful person.
Do you mind adding timestamp and backup file name into logging, would be great I think.

Cheers,
earthpwn

**Comment by Tospaa** [comment]
I'm on it! Glad you liked it abe!

**Comment by Tospaa** [comment]
Hello earthpwn,

I've done what you asked me for, and more! I've took the liberty to change the generic backup name. I didn't remove the old format(because, you know, backward compatibility), but I think you'll love the new one. Flip the LEGACY varible to False in the code to see the changes :).

Thanks for being interested and your advices.

Cheers,
Tospaa
